### ISSUE TITLE
Algo 1 

### ISSUE THREAD

**Issue by SumeetKamble1503** [y4sh-patel/M-Colouring-Problem#2]
Issue in taking input 
Code is terminated before entire set of values is taken as input
input file 
10
3
15
1 2
1 3
1 6
2 7
2 8
3 4
3 9
4 5
4 8
5 6
5 7
5 10
6 9
7 10
8 10
![image](https://user-images.githubusercontent.com/51257281/112720104-746ea380-8f22-11eb-8746-75745342a0ef.png)

**Comment by y4sh-patel** [comment]
The program is written on 0 based indexing.
Try 
10
3
15
0 1
0 2
0 5
1 6
1 7
2 3
2 8
3 4
3 7
4 5
4 6
4 9
5 8
6 9
7 9


Revert if Issue still arise.

**Comment by y4sh-patel** [comment]
Hope this might help.

[](url)
<img width="1027" alt="Screenshot 2021-03-27 at 5 37 04 PM" src="https://user-images.githubusercontent.com/56584149/112720230-1bebd600-8f23-11eb-9126-2018f52af932.png">

**Comment by SumeetKamble1503** [comment]
Perfectly Fine !
We should update the Code by making it's Indexing Based on 1
To make it more user Friendly !
